apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-vote-api
  name: pipelines-vote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-vote-api
  template:
    metadata:
      labels:
        app: pipelines-vote-api
    spec:
      containers:
        - image: quay-registry-quay-quay-registry.apps.cluster-2hr49.2hr49.sandbox1208.opentlc.com/user1/demo-secure-images:v1
          imagePullPolicy: Always
          name: pipelines-vote-api
          ports:
            - containerPort: 9000
              protocol: TCP
